language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/'

script: "mvn clean package -Preal -DskipTests"

before_deploy:
  - zip -r my-spring-boot-dashboard *
  - mkdir -p deploy
  - mv my-spring-boot-dashboard.zip deploy/my-spring-boot-dashboard.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-spring-boot-dashboard-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: my-spring-boot-dashboard-build
    key: my-spring-boot-dashboard.zip
    bundle_type: zip
    application: my-spring-boot-dashboard
    deployment_group: my-spring-boot-dash-board-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - jby0711823@naver.com
