language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/'

script: "mvn clean package -Preal -DskipTests"

notifications:
  email:
    recipients:
      - jby0711823@naver.com