spring:
  profiles:
    include: oauth # oauth profile의 properties 설정들을 포함
  datasource:
    url: jdbc:h2:mem:testdb # h2-console에 접근하기 위해서 필요
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # dialect 잘못 설정시 프로그램 실행되지 않음
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
